[tools]
poetry = {version='latest', pyproject='pyproject.toml'}
python = '3.10.4' # must be after poetry so the poetry bin is first in PATH
pipx = "latest"

[env]
MISE_POETRY_AUTO_INSTALL = 1
NO_GEVENT = 1
