version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: farm_perfect_db
    environment:
      POSTGRES_DB: farm_perfect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgis:/var/lib/postgresql/data

  web:
    build: .
    container_name: farm_perfect_web
    command: python farm_perfect/manage.py runserver 0.0.0.0:8000  # Corrected path to manage.py
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
      - DATABASE_URL=postgres://postgres:your_password_here@db:5432/farm_perfect
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
      - GEOS_LIBRARY_PATH=/usr/lib/libgeos_c.so
